<a href="https://colab.research.google.com/github/cgoyal23/Customer_Churn_Analysis/blob/main/Copy_of_Assignment_1_1_by_chirag.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1.1 - Pandas Data Analysis Practice

*This assignment is a part of the project ["Customer Churn Analysis: From Data To Strategy"]*

In this assignment, you'll get to practice some of the concepts and skills covered in pandas.

As you go through this notebook, you will find a **???** in certain places. To complete this assignment, you must replace all the **???** with appropriate values, expressions or statements to ensure that the notebook runs properly end-to-end.

Some things to keep in mind:

* Do not change variable names, delete cells or disturb other existing code. It may cause problems during evaluation.
* In some cases, you may need to add some code cells or new statements before or after the line of code containing the **???**.
* Questions marked **(Optional)** will not be considered for evaluation, and can be skipped. They are for your learning.


If you are stuck, you can ask for help on the Whatsapp group. Please do not use **ChatGPT or any other LLM to get solutions to the questions.**


Deadline : **22 May, 11:59 pm**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In this assignment, we're going to analyze an operate on data from a CSV file. Let's begin by downloading the CSV file.

Let's load the data from the CSV file into a Pandas data frame.

In [ ]:
countries_df = pd.read_csv('countries.csv')

In [ ]:
countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,Afghanistan,Asia,38928341,64.83,0.50,1803.987
1,Albania,Europe,2877800,78.57,2.89,11803.431
2,Algeria,Africa,43851043,76.88,1.90,13913.839
3,Andorra,Europe,77265,83.73,NaN,NaN
4,Angola,Africa,32866268,61.15,NaN,5819.495
...,...,...,...,...,...,...
205,Vietnam,Asia,97338583,75.40,2.60,6171.884
206,Western Sahara,Africa,597330,70.26,NaN,NaN
207,Yemen,Asia,29825968,66.12,0.70,1479.147
208,Zambia,Africa,18383956,63.89,2.00,3689.251
209,Zimbabwe,Africa,14862927,61.49,1.70,1899.775

**Q1: How many countries does the dataframe contain?**

Hint: Use the `.shape` method.

In [ ]:
num_countries = countries_df.shape[0]

In [ ]:
print('There are {} countries in the dataset'.format(num_countries))

There are 210 countries in the dataset

**Q2: Retrieve a list of continents from the dataframe?**

*Hint: Use the `.unique` method of a series.*

In [ ]:
continents = countries_df["continent"].unique()

In [ ]:
continents

array(['Asia', 'Europe', 'Africa', 'North America', 'South America',
       'Oceania'], dtype=object)

**Q3: What is the total population of all the countries listed in this dataset?**

In [ ]:
total_population = countries_df["population"].sum()

In [ ]:
print('The total population is {}.'.format(int(total_population)))

The total population is 7757980095.

**Q: (Optional) What is the overall life expectancy across in the world?**

*Hint: You'll need to take a weighted average of life expectancy using populations as weights.*

In [ ]:
x= countries_df["population"]

In [ ]:
y= countries_df["life_expectancy"]

In [ ]:
mean= ((x*y).sum())/x.sum()

In [ ]:
mean

72.72165193409664

**Q4: Create a dataframe containing 10 countries with the highest population.**

*Hint: Chain the `sort_values` and `head` methods.*

In [ ]:
most_populous_df = countries_df.sort_values(by="population")

In [ ]:
a=most_populous_df.tail(10)

In [ ]:
a.iloc[::-1]

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
41,China,Asia,1439323774,76.91,4.34,15308.712
90,India,Asia,1380004385,69.66,0.53,6426.674
199,United States,North America,331002647,78.86,2.77,54225.446
91,Indonesia,Asia,273523621,71.72,1.04,11188.744
145,Pakistan,Asia,220892331,67.27,0.60,5034.708
27,Brazil,South America,212559409,75.88,2.20,14103.452
141,Nigeria,Africa,206139587,54.69,NaN,5338.454
15,Bangladesh,Asia,164689383,72.59,0.80,3523.984
157,Russia,Europe,145934460,72.58,8.05,24765.954
125,Mexico,North America,128932753,75.05,1.38,17336.469

**Q5: Add a new column in `countries_df` to record the overall GDP per country (product of population & per capita GDP).**

In [ ]:
countries_df['gdp'] = countries_df["gdp_per_capita"]*countries_df['population']

In [ ]:
countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
0,Afghanistan,Asia,38928341,64.83,0.50,1803.987,7.022622e+10
1,Albania,Europe,2877800,78.57,2.89,11803.431,3.396791e+10
2,Algeria,Africa,43851043,76.88,1.90,13913.839,6.101364e+11
3,Andorra,Europe,77265,83.73,NaN,NaN,NaN
4,Angola,Africa,32866268,61.15,NaN,5819.495,1.912651e+11
...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583,75.40,2.60,6171.884,6.007624e+11
206,Western Sahara,Africa,597330,70.26,NaN,NaN,NaN
207,Yemen,Asia,29825968,66.12,0.70,1479.147,4.411699e+10
208,Zambia,Africa,18383956,63.89,2.00,3689.251,6.782303e+10
209,Zimbabwe,Africa,14862927,61.49,1.70,1899.775,2.823622e+10

** ***bold text***Q: (Optional) Create a dataframe containing 10 countries with the lowest GDP per capita, among the counties with population greater than 100 million.**

In [ ]:
drop_down= countries_df[countries_df["population"]>100000000]

In [ ]:
cc= drop_down.sort_values(by="gdp_per_capita")

In [ ]:
cc.head(10)

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
63,Ethiopia,Africa,114963583,66.60,0.30,1729.927,1.988786e+11
15,Bangladesh,Asia,164689383,72.59,0.80,3523.984,5.803628e+11
145,Pakistan,Asia,220892331,67.27,0.60,5034.708,1.112128e+12
141,Nigeria,Africa,206139587,54.69,NaN,5338.454,1.100467e+12
90,India,Asia,1380004385,69.66,0.53,6426.674,8.868838e+12
151,Philippines,Asia,109581085,71.23,1.00,7599.188,8.327273e+11
58,Egypt,Africa,102334403,71.99,1.60,10550.206,1.079649e+12
91,Indonesia,Asia,273523621,71.72,1.04,11188.744,3.060386e+12
27,Brazil,South America,212559409,75.88,2.20,14103.452,2.997821e+12
41,China,Asia,1439323774,76.91,4.34,15308.712,2.203419e+13

**Q6: Create a data frame that counts the number countries in each continent?**

*Hint: Use `groupby`, select the `location` column and aggregate using `count`.*

In [ ]:
country_counts_df = countries_df.groupby(["continent"])["continent"].count()

In [ ]:
country_counts_df

continent
Africa           55
Asia             47
Europe           51
North America    36
Oceania           8
South America    13
Name: continent, dtype: int64

**Q7: Create a data frame showing the total population of each continent.**

*Hint: Use `groupby`, select the population column and aggregate using `sum`.*

In [ ]:
continent_populations_df = countries_df.groupby(["continent"])["population"].sum()

In [ ]:
continent_populations_df

continent
Africa           1339423921
Asia             4607388081
Europe            748506210
North America     591242473
Oceania            40958320
South America     430461090
Name: population, dtype: int64

Let's download another CSV file containing overall Covid-19 stats for various countires, and read the data into another Pandas data frame.

In [ ]:
covid_data_df = pd.read_csv('covid-countries-data.csv')

In [ ]:
covid_data_df

           location  total_cases  total_deaths  total_tests
0       Afghanistan      38243.0        1409.0          NaN
1           Albania       9728.0         296.0          NaN
2           Algeria      45158.0        1525.0          NaN
3           Andorra       1199.0          53.0          NaN
4            Angola       2729.0         109.0          NaN
..              ...          ...           ...          ...
207  Western Sahara        766.0           1.0          NaN
208           World   26059065.0      863535.0          NaN
209           Yemen       1976.0         571.0          NaN
210          Zambia      12415.0         292.0          NaN
211        Zimbabwe       6638.0         206.0      97272.0

[212 rows x 4 columns]

**Q8: Count the number of countries for which the `total_tests` data is missing.**

*Hint: Use the `.isna` method.*

In [ ]:
total_tests_missing = covid_data_df["total_tests"].isnull().sum()

In [ ]:
print("The data for total tests is missing for {} countries.".format(int(total_tests_missing)))

The data for total tests is missing for 122 countries.

Let's merge the two data frames, and compute some more metrics.

**Q9: Merge `countries_df` with `covid_data_df` on the `location` column.**

*Hint: Use the `.merge` method on `countries_df`.

In [ ]:
combined_df = pd.merge(countries_df,covid_data_df,on="location")

In [ ]:
combined_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp,total_cases,total_deaths,total_tests
0,Afghanistan,Asia,38928341,64.83,0.50,1803.987,7.022622e+10,38243.0,1409.0,NaN
1,Albania,Europe,2877800,78.57,2.89,11803.431,3.396791e+10,9728.0,296.0,NaN
2,Algeria,Africa,43851043,76.88,1.90,13913.839,6.101364e+11,45158.0,1525.0,NaN
3,Andorra,Europe,77265,83.73,NaN,NaN,NaN,1199.0,53.0,NaN
4,Angola,Africa,32866268,61.15,NaN,5819.495,1.912651e+11,2729.0,109.0,NaN
...,...,...,...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583,75.40,2.60,6171.884,6.007624e+11,1046.0,35.0,261004.0
206,Western Sahara,Africa,597330,70.26,NaN,NaN,NaN,766.0,1.0,NaN
207,Yemen,Asia,29825968,66.12,0.70,1479.147,4.411699e+10,1976.0,571.0,NaN
208,Zambia,Africa,18383956,63.89,2.00,3689.251,6.782303e+10,12415.0,292.0,NaN
209,Zimbabwe,Africa,14862927,61.49,1.70,1899.775,2.823622e+10,6638.0,206.0,97272.0

**Q10: Add columns `tests_per_million`, `cases_per_million` and `deaths_per_million` into `combined_df`.**

In [ ]:
combined_df['tests_per_million'] = combined_df['total_tests'] * 1e6 / combined_df['population']

In [ ]:
combined_df['cases_per_million'] = combined_df['total_cases'] * 1e6 / combined_df['population']

In [ ]:
combined_df['deaths_per_million'] = combined_df['total_deaths'] * 1e6 / combined_df['population']

In [ ]:
combined_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
0,Afghanistan,Asia,38928341,64.83,0.50,1803.987,7.022622e+10,38243.0,1409.0,NaN,NaN,982.394806,36.194710
1,Albania,Europe,2877800,78.57,2.89,11803.431,3.396791e+10,9728.0,296.0,NaN,NaN,3380.359997,102.856349
2,Algeria,Africa,43851043,76.88,1.90,13913.839,6.101364e+11,45158.0,1525.0,NaN,NaN,1029.804468,34.776824
3,Andorra,Europe,77265,83.73,NaN,NaN,NaN,1199.0,53.0,NaN,NaN,15518.022390,685.950948
4,Angola,Africa,32866268,61.15,NaN,5819.495,1.912651e+11,2729.0,109.0,NaN,NaN,83.033462,3.316470
...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583,75.40,2.60,6171.884,6.007624e+11,1046.0,35.0,261004.0,2681.403324,10.745996,0.359570
206,Western Sahara,Africa,597330,70.26,NaN,NaN,NaN,766.0,1.0,NaN,NaN,1282.373228,1.674116
207,Yemen,Asia,29825968,66.12,0.70,1479.147,4.411699e+10,1976.0,571.0,NaN,NaN,66.250993,19.144391
208,Zambia,Africa,18383956,63.89,2.00,3689.251,6.782303e+10,12415.0,292.0,NaN,NaN,675.317108,15.883415
209,Zimbabwe,Africa,14862927,61.49,1.70,1899.775,2.823622e+10,6638.0,206.0,97272.0,6544.605918,446.614587,13.859989

**Q11: Create a dataframe with 10 countires that have highest number of tests per million people.**

In [ ]:
highest_tests_df = combined_df.sort_values(by="tests_per_million").tail(10)

In [ ]:
highest_tests_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
189,Timor,Asia,1318442,69.50,5.9,6570.102,8.662298e+09,27.0,0.0,NaN,NaN,20.478717,0.000000
191,Trinidad and Tobago,North America,1399491,73.51,3.0,28763.071,4.025366e+10,1920.0,28.0,NaN,NaN,1371.927365,20.007274
194,Turks and Caicos Islands,North America,38718,80.22,NaN,NaN,NaN,555.0,4.0,NaN,NaN,14334.418100,103.311121
200,United States Virgin Islands,North America,104423,80.58,NaN,NaN,NaN,1144.0,15.0,NaN,NaN,10955.440851,143.646515
202,Uzbekistan,Asia,33469199,71.72,4.0,6253.104,2.092864e+11,42540.0,329.0,NaN,NaN,1271.019363,9.829933
203,Vatican,Europe,809,75.12,NaN,NaN,NaN,12.0,0.0,NaN,NaN,14833.127318,0.000000
204,Venezuela,South America,28435943,72.06,0.8,16745.022,4.761605e+11,48883.0,398.0,NaN,NaN,1719.056759,13.996371
206,Western Sahara,Africa,597330,70.26,NaN,NaN,NaN,766.0,1.0,NaN,NaN,1282.373228,1.674116
207,Yemen,Asia,29825968,66.12,0.7,1479.147,4.411699e+10,1976.0,571.0,NaN,NaN,66.250993,19.144391
208,Zambia,Africa,18383956,63.89,2.0,3689.251,6.782303e+10,12415.0,292.0,NaN,NaN,675.317108,15.883415

**Q12: Create a dataframe with 10 countires that have highest number of positive cases per million people.**

In [ ]:
highest_cases_df = combined_df.sort_values(by="total_cases").tail(10)

In [ ]:
highest_cases_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
177,Spain,Europe,46754783,83.56,2.97,34272.360,1.602397e+12,479554.0,29194.0,6416533.0,137238.001939,10256.790198,624.406705
125,Mexico,North America,128932753,75.05,1.38,17336.469,2.235239e+12,610957.0,65816.0,1271295.0,9860.140037,4738.570967,510.467654
174,South Africa,Africa,59308690,64.13,2.32,12294.876,7.291930e+11,630595.0,14389.0,3705408.0,62476.645497,10632.421657,242.612002
42,Colombia,South America,50882884,77.29,1.71,13254.949,6.744500e+11,633339.0,20348.0,2647702.0,52035.218758,12446.994946,399.898716
150,Peru,South America,32971846,76.74,1.60,12236.706,4.034668e+11,663437.0,29259.0,584232.0,17719.117092,20121.318048,887.393445
157,Russia,Europe,145934460,72.58,8.05,24765.954,3.614206e+12,1005000.0,17414.0,37176827.0,254750.159763,6886.653091,119.327539
90,India,Asia,1380004385,69.66,0.53,6426.674,8.868838e+12,3853406.0,67376.0,44337201.0,32128.304433,2792.314316,48.823033
27,Brazil,South America,212559409,75.88,2.20,14103.452,2.997821e+12,3997865.0,123780.0,4797948.0,22572.268255,18808.224105,582.331314
199,United States,North America,331002647,78.86,2.77,54225.446,1.794877e+13,6114406.0,185744.0,83898416.0,253467.507769,18472.377957,561.155633
87,Hong Kong,Asia,7496988,84.86,NaN,56054.920,4.202431e+11,NaN,NaN,780410.0,104096.471810,NaN,NaN

**Q13: Create a dataframe with 10 countires that have highest number of deaths cases per million people?**

In [ ]:
highest_deaths_df = combined_df.sort_values(by="deaths_per_million").tail(10)

In [ ]:
highest_deaths_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
27,Brazil,South America,212559409,75.88,2.20,14103.452,2.997821e+12,3997865.0,123780.0,4797948.0,22572.268255,18808.224105,582.331314
97,Italy,Europe,60461828,83.51,3.18,35220.084,2.129471e+12,271515.0,35497.0,5214766.0,86248.897403,4490.684602,587.097697
40,Chile,South America,19116209,80.18,2.11,22767.037,4.352194e+11,414739.0,11344.0,2458762.0,128621.841287,21695.671982,593.423100
198,United Kingdom,Europe,67886004,81.32,2.54,39753.244,2.698689e+12,338676.0,41514.0,13447568.0,198090.434075,4988.892850,611.525168
177,Spain,Europe,46754783,83.56,2.97,34272.360,1.602397e+12,479554.0,29194.0,6416533.0,137238.001939,10256.790198,624.406705
3,Andorra,Europe,77265,83.73,NaN,NaN,NaN,1199.0,53.0,NaN,NaN,15518.022390,685.950948
18,Belgium,Europe,11589616,81.63,5.64,42658.576,4.943965e+11,85817.0,9898.0,2281853.0,196887.713967,7404.645676,854.040375
150,Peru,South America,32971846,76.74,1.60,12236.706,4.034668e+11,663437.0,29259.0,584232.0,17719.117092,20121.318048,887.393445
162,San Marino,Europe,33938,84.97,3.80,56861.470,1.929765e+09,735.0,42.0,NaN,NaN,21657.139490,1237.550828
87,Hong Kong,Asia,7496988,84.86,NaN,56054.920,4.202431e+11,NaN,NaN,780410.0,104096.471810,NaN,NaN

**(Optional) Q: Count number of countries that feature in both the lists of "highest number of tests per million" and "highest number of cases per million".**

In [ ]:
pd.merge(highest_cases_df,highest_deaths_df,on="location").shape[0]

4

**(Optional) Q: Count number of countries that feature in both the lists "20 countries with lowest GDP per capita" and "20 countries with the lowest number of hospital beds per thousand population". Only consider countries with a population higher than 10 million while creating the list.**

In [ ]:
cc= combined_df[combined_df['population']>100000000]

In [ ]:
cc1=combined_df.sort_values(by="gdp_per_capita").head(20)

In [ ]:
cc2=combined_df.sort_values(by="hospital_beds_per_thousand").head(20)

In [ ]:
pd.merge(cc1,cc2,on="location").shape[0]

10

## Submission

Congratulations on making it this far! You've reached the end of this assignment, and you just completed your first real-world data analysis problem.

In [ ]:
print("Thank you so much")

Thank you so much